import type { Lead } from "./types";

export const seedLeads: Lead[] = [
  {
    id: "1",
    company: "Acme Corp",
    contactName: "Maria Santos",
    email: "maria@acme.com",
    phone: "+63 912 345 6789",
    value: 12000,
    status: "new",
    priority: "high",
    nextFollowUp: "2026-05-12",
    notes: "Interested in a dashboard for their sales team.",
    createdAt: "2026-05-07",
  },
  {
    id: "2",
    company: "Northstar Digital",
    contactName: "James Lee",
    email: "james@northstar.com",
    phone: "+63 917 222 4433",
    value: 8500,
    status: "proposal",
    priority: "medium",
    nextFollowUp: "2026-05-14",
    notes: "Waiting for decision after proposal review.",
    createdAt: "2026-05-07",
  },
  {
    id: "3",
    company: "Bright Foods",
    contactName: "Ana Reyes",
    email: "ana@brightfoods.com",
    phone: "+63 908 111 2299",
    value: 5000,
    status: "contacted",
    priority: "low",
    nextFollowUp: "2026-05-10",
    notes: "Requested a quick intro call next week.",
    createdAt: "2026-05-07",
  },
];
